# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - 
- script: |
    curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
    echo Unified Agent downloaded successfully
    java -jar wss-unified-agent.jar
  env:
    WS_APIKEY: 250865dd939049cabc5c954806c92f5f03ba0bb0398b4739980edc84374af819
    WS_WSS_URL: https://saas.whitesourcesoftware.com/Wss/WSS.html/
    WS_PRODUCTNAME: WebGoat_Azure_1
    WS_PROJECTNAME: WebGoat_Azure
    resolveAllDependencies: true
    maven.resolveDependencies: true
    maven.downloadMissingDependencies: true
    

  displayName: 'WhiteSource Unified Agent Scan'